#!/bin/sh

#
# Copyright © 2015-2021 the original authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

##############################################################################
#
#   Gradle start up script for POSIX generated by Gradle.
#
#   Important for running:
#
#   (1) You need a POSIX-compliant shell to run this script. If your /bin/sh is
#       noncompliant, but you have some other compliant shell such as ksh or
#       bash, then you need to set the SHELL environment variable to point to
#       that shell before running this script, like this:
#           SHELL=/bin/bash ./gradlew
#
#       The "cygwin" and "msys" environments are known to be noncompliant.
#
#   (2) This script does not support the "cygwin" or "msys" environments, and
#       the "MINGW" environment also has known issues. Therefore we do not
#       recommend using these environments. To use this script in these
#       environments, you can try making modifications, or use a different
#       shell (e.g. "bash") and hope it works.
#
#   (3) This script uses the "uname" command, which might not work in some
#       non-POSIX environments. If that's the case, you can manually set the
#       "os" variable in the script to the correct operating system name.
#
#   (4) This script attempts to use the "java" command to find the Java
#       runtime. If you are using a non-standard Java installation, you may
#       need to set the "JAVA_HOME" environment variable.
#
#   (5) This script uses the "basename" and "dirname" commands, which are
#       part of the POSIX standard. If these commands are not available, you
#       may need to install them.
#
#   (6) This script automatically sets the "org.gradle.jvmargs" property to
#       increase the maximum heap size. If you want to customize this value,
#       you can set the "GRADLE_OPTS" environment variable.
#
##############################################################################

# Attempt to set APP_HOME

# Resolve links: $0 may be a link
app_path=$0

# Need this for daisy-chained symlinks.
while
    APP_HOME=${app_path%"${app_path##*/}"}  # leaves a trailing /; empty if no leading path
    [ -h "$app_path" ]
do
    ls=$( ls -ld "$app_path" )
    link=${ls#*' -> '}
    case $link in             #(
      /*)   app_path=$link ;; #(
      *)    app_path=$APP_HOME$link ;;
    esac
done

APP_HOME=$( cd "${APP_HOME:-./}" && pwd -P ) || exit

# Add default JVM options here. You can also use JAVA_OPTS and GRADLE_OPTS to pass JVM options to this script.
DEFAULT_JVM_OPTS='"-Xmx64m" "-Xms64m"'

# Use the maximum available, or set MAX_FD != -1 to use that value.
MAX_FD=maximum

warn () {
    echo "$*"
} >&2

die () {
    echo
    echo "$*"
    echo
    exit 1
} >&2

# OS specific support (must be 'true' or 'false').
cygwin=false
msys=false
mingw=false
case "$( uname )" in                #(
  CYGWIN* )         cygwin=true  ;; #(
  MINGW* )          mingw=true   ;; #(
  MSYS* )           msys=true    ;; #(
  * )                               ;;
esac

# Determine the Java command to use to start the JVM.
if [ -n "$JAVA_HOME" ] ; then
    if [ -x "$JAVA_HOME/jre/sh/java" ] ; then
        # IBM's JDK on AIX uses strange locations for the executables
        JAVACMD=$JAVA_HOME/jre/sh/java
    else
        JAVACMD=$JAVA_HOME/bin/java
    fi
    if [ ! -x "$JAVACMD" ] ; then
        die "ERROR: JAVA_HOME is set to an invalid directory: $JAVA_HOME

Please set the JAVA_HOME variable in your environment to match the
location of your Java installation."
    fi
else
    JAVACMD=java
    which java >/dev/null 2>&1 || die "ERROR: JAVA_HOME is not set and no 'java' command could be found in your PATH.

Please set the JAVA_HOME variable in your environment to match the
location of your Java installation."
fi

# Increase the maximum file descriptors if we can.
if ! "$cygwin" && ! "$msys" && ! "$mingw" ; then
    case $MAX_FD in #(
      max*)
        MAX_FD=$( ulimit -H -n ) ||
            warn "Could not query maximum file descriptor limit"
    esac
    case $MAX_FD in  #(
      '' | soft) :;; #(
      *)
        ulimit -n "$MAX_FD" ||
            warn "Could not set maximum file descriptor limit to $MAX_FD"
    esac
fi

# Collect all arguments for the java command, stacking in reverse order:
#   * args from the command line
#   * the main class name
#   * the classpath 'gradle-launcher-*.jar'

# For Cygwin or MSYS, switch paths to Windows format before running java
if "$cygwin" || "$msys" ; then
    APP_HOME=$( cygpath --path --mixed "$APP_HOME" )
    CLASSPATH=$( cygpath --path --mixed "$CLASSPATH" )

    JAVACMD=$( cygpath --unix "$JAVACMD" )

    # Now convert the arguments - we need a workaround for the fact that
    # cygwin and msys treat single quotes and spaces differently.
    # See https://github.com/gradle/gradle/issues/17317
    # Although we only need to quote arguments that contain spaces, we
    # quote all of them for safety.
    #
    # It is also necessary to add an extra layer of escaping for the
    # first argument if it contains a space.
    #
    # The following loop quotes each argument, escapes backslashes and
    # quotes in the argument with backslash, and breaks the argument if
    # it contains a newline (which cannot be passed through reliably).
    #
    # We use the _dummy variable to preserve the correct number of
    # arguments.
    for _dummy in "${@}" ; do
        arg=${_dummy}
        if [ $# -gt 1 ] ; then
            arg="\"$arg\""
        fi
        # Replace each backslash with two backslashes,
        # so that they are not removed when the arg is split into
        # words by the "sh" or "bash" shell.
        arg=$( echo "$arg" | sed 's/\\/\\\\/g' )
        # Replace each double quote that is not already escaped
        # with a backslash-escaped double quote.
        arg=$( echo "$arg" | sed 's/\(^\|[^\\]\)"/\1\\"/g' )
        # Add the argument to the list.
        GRADLE_COMMAND_ARGS="$GRADLE_COMMAND_ARGS \"$arg\""
    done
fi

# Collect all arguments for the java command;
#   * $DEFAULT_JVM_OPTS, $JAVA_OPTS, and $GRADLE_OPTS can contain fragments of
#     shell script including quotes and variable substitutions, so put them in
#     double quotes to make sure that they get re-expanded; and
#   * put everything else in single quotes, so that it's not re-expanded.

set -- \
        "-Dorg.gradle.appname=$APP_BASE_NAME" \
        -classpath "$CLASSPATH" \
        org.gradle.wrapper.GradleWrapperMain \
        "$@"

# Use "xargs" to parse quoted args.
#
# With -n1 it outputs one arg per line, with the quotes and backslashes removed.
#
# In Bash we could simply go:
#
#   readarray ARGS < <( xargs -n1 <<<"$var" ) &&
#   set -- "${ARGS[@]}" "$@"
#
# but POSIX shell has neither arrays nor command substitution, so instead we
# post-process each arg (as a line of input to sed) to backslash-escape any
# character that might be a shell metacharacter, then use eval to reverse
# that process (while maintaining the separation between arguments), and wrap
# the whole thing up as a single "set" statement.
#
# This will of course break if any of these variables contains a newline or
# an unmatched quote.
#

eval "set -- $(
        printf '%s\n' "$DEFAULT_JVM_OPTS $JAVA_OPTS $GRADLE_OPTS" |
        xargs -n1 |
        sed ' s~[^-[:alnum:]+,./:=@_]~\\&~g; ' |
        tr '\n' ' '
    )" '"$@"'

exec "$JAVACMD" "$@"
